# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4c9127410c46b7d888e1f2c0b8ed1945926c03dd4d00d4e32ab37467bd0b45407636d085eb9118960d1496e8ec24c8aa20e3e2905edaedd9399bf073c4cf7f8

test:
  secret_key_base: dbddee4ec6aa2e59ac8d972106fa80627049692c87be02874d8e5a781ea15949080b8c0a67b3e180dbcba51f85579ffe68379f6583615f8589efba8b8353e18f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
